// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgFG0q02uzCGwSPsXgjv_BVaevKzhUls',
    appId: '1:1096954431507:web:cf705610970b43339f57e6',
    messagingSenderId: '1096954431507',
    projectId: 'park-project-3cd64',
    authDomain: 'park-project-3cd64.firebaseapp.com',
    storageBucket: 'park-project-3cd64.appspot.com',
    measurementId: 'G-7TT6T9JMWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASuBwvSdO5A-YmZb8AmoniUBQ0RzMAaj4',
    appId: '1:1096954431507:android:1e42d42fdcaece249f57e6',
    messagingSenderId: '1096954431507',
    projectId: 'park-project-3cd64',
    storageBucket: 'park-project-3cd64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO26ZktL8uDsGLitkcN0Jr96yN4dl6BO4',
    appId: '1:1096954431507:ios:2b295ff2ac88c5bd9f57e6',
    messagingSenderId: '1096954431507',
    projectId: 'park-project-3cd64',
    storageBucket: 'park-project-3cd64.appspot.com',
    iosBundleId: 'com.example.parkingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO26ZktL8uDsGLitkcN0Jr96yN4dl6BO4',
    appId: '1:1096954431507:ios:2b295ff2ac88c5bd9f57e6',
    messagingSenderId: '1096954431507',
    projectId: 'park-project-3cd64',
    storageBucket: 'park-project-3cd64.appspot.com',
    iosBundleId: 'com.example.parkingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCgFG0q02uzCGwSPsXgjv_BVaevKzhUls',
    appId: '1:1096954431507:web:1d1b4e20e2fe21ac9f57e6',
    messagingSenderId: '1096954431507',
    projectId: 'park-project-3cd64',
    authDomain: 'park-project-3cd64.firebaseapp.com',
    storageBucket: 'park-project-3cd64.appspot.com',
    measurementId: 'G-EKMEG3YGVV',
  );
}
